### PR TITLE
chore: upgrade go to 1.19

### PR DESCRIPTION
**Pull request by hezhizhen**

### CODE REVIEW

**Comment by caoxianfei1** [comment]
@hezhizhen Why do you want to upgrade golang version?

**Comment by hezhizhen** [comment]
> @hezhizhen Why do you want to upgrade golang version?

Since v1.18 has reached end of life: https://endoflife.date/go

**Comment by caoxianfei1** [comment]
We will try our best to consider the compatibility of the user environment. It may be hard to upgrade the application version.

**Comment by caoxianfei1** [comment]
> > @hezhizhen Why do you want to upgrade golang version?
> 
> Since v1.18 has reached end of life: https://endoflife.date/go


We will try our best to consider the compatibility of the user environment. It may be hard to upgrade the application version.

**Comment by hezhizhen** [comment]
> > > @hezhizhen Why do you want to upgrade golang version?
> > 
> > 
> > Since v1.18 has reached end of life: https://endoflife.date/go
> 
> We will try our best to consider the compatibility of the user environment. It may be hard to upgrade the application version.

I see. Sorry for the rush PR. Close as you wish.

**Pull request closed without merging**
