### PR TITLE
Feat: upgrade go version 1.18

### PR DESCRIPTION
**Pull request by fengshunli**

### CODE REVIEW

**Review by caoxianfei1 — COMMENTED** [review]
compile success?

**Comment by fengshunli** [comment]
> compile success?

yes

**Comment by caoxianfei1** [comment]
> > compile success?
> 
> yes



> > compile success?
> 
> yes

you can `make run` for test.

**Comment by fengshunli** [comment]
> > > compile success?
> > 
> > 
> > yes
> 
> > > compile success?
> > 
> > 
> > yes
> 
> you can `make run` for test.

make test ok

**Comment by fengshunli** [comment]
image
make run ok

**Review by caoxianfei1 — COMMENTED** [review]
go1.18 cannot download `kustomize` to `GOBIN`, need to modify the `Makefile` and test again.

**Comment by fengshunli** [comment]
use local kustomize

**Comment by caoxianfei1** [comment]
> use local kustomize

it is necessary to ensure `make kustomize` work.

**Comment by fengshunli** [comment]
> make kustomize

image
everything is normal @caoxianfei1

**Comment by caoxianfei1** [comment]
Older version should work under newer versions of the Go compiler without changes. However, new programs may not compile under older versions of the Go compiler. Is an upgrade necessary?

**Comment by fengshunli** [comment]
Yes, you need to upgrade go version 1.18 or above

**Comment by caoxianfei1** [comment]
> > make kustomize
> 
> image everything is normal @caoxianfei1

make run cannot trigger download kustomize. you can execute `make kustomize` to verify

**Comment by caoxianfei1** [comment]
> > > make kustomize
> > 
> > 
> > image everything is normal @caoxianfei1
> 
> make run cannot trigger download kustomize. you can delete local kustomize and execute `make kustomize` to verify.

**Comment by fengshunli** [comment]
> > > > make kustomize
> > > 
> > > 
> > > image everything is normal @caoxianfei1
> > 
> > 
> > make run cannot trigger download kustomize. you can delete local kustomize and execute `make kustomize` to verify.



> > > > make kustomize
> > > 
> > > 
> > > image everything is normal @caoxianfei1
> > 
> > 
> > make run cannot trigger download kustomize. you can delete local kustomize and execute `make kustomize` to verify.

image

You can't go get here, you need go install to install it before it can be executed @caoxianfei1

**Comment by fengshunli** [comment]
@caoxianfei1 merge

**Review by caoxianfei1 — COMMENTED** [review]
the Dockerfile need to update golang version to 1.18 together not to a new pr.

**Comment by fengshunli** [comment]
> the Dockerfile need to update golang version to 1.18 together not to a new pr.

done @caoxianfei1

**Review by caoxianfei1 — APPROVED** [review]
lgtm

**Pull request merged**
